quarkus.mongodb.database=sportsfacility
quarkus.mongodb.connection-string=mongodb://admin:adminpassword@localhost:27017,localhost:27018,localhost:27019/sportsfacility?replicaSet=sportsfacility_set_single&authSource=admin

quarkus.jackson.write-dates-as-timestamps=false

quarkus.log.category."sfs".level=DEBUG